import type { MarkdownHeading } from 'astro'

export interface TocItem extends MarkdownHeading {
  children: TocItem[]
}

interface TocOpts {
  /** Shallowest heading to include. Defaults to h2 — h1 is the page title. */
  minHeadingLevel?: number
  /** Deepest heading to include. Defaults to h3; h4 and below make a wall. */
  maxHeadingLevel?: number
}

/**
 * Convert the flat headings array generated by Astro into a nested tree structure.
 *
 * The bounds are optional because the defaults are the only values anything
 * uses. They were written as defaults on a required field, which reads as a
 * default and behaves as dead code — `oxlint --type-aware` flags exactly that.
 */
export function generateToC(
  headings: MarkdownHeading[],
  { minHeadingLevel = 2, maxHeadingLevel = 3 }: TocOpts = {},
): TocItem[] {
  const filtered = headings.filter(({ depth }) => depth >= minHeadingLevel && depth <= maxHeadingLevel)

  const toc: TocItem[] = []

  // Don't add the page title as it doesn't have a matching ID in the document
  // Just use the actual headings from the markdown
  for (const heading of filtered) {
    injectChild(toc, { ...heading, children: [] })
  }

  return toc
}

/** Inject a ToC entry as deep in the tree as its `depth` property requires. */
function injectChild(items: TocItem[], item: TocItem): void {
  const lastItem = items.at(-1)
  if (!lastItem || lastItem.depth >= item.depth) {
    items.push(item)
  } else {
    injectChild(lastItem.children, item)
  }
}
