/** Source-verified relationships across ports; similar spelling does not prove matching behavior. */
export interface Concept {
  /** What the operation does, in one line, in no particular language. */
  label: string
  /** Public id of the symbol implementing it, per port. */
  symbols: Record<string, string>
  /** Why a port is missing, when it is. */
  absent?: Record<string, string>
}

export const CONCEPTS: Record<string, Concept> = {
  server: {
    label: 'A tmux server',
    symbols: {
      py: 'libtmux.Server',
      ts: 'server.Server',
      rs: 'server.Server',
      go: 'tmux.Server',
      java: 'io.github.libtmux.Server.Server',
      dotnet: 'LibTmux.Server',
      cxx: 'libtmux::Server',
      swift: 'Server',
    },
  },
  session: {
    label: 'A tmux session',
    symbols: {
      py: 'libtmux.Session',
      ts: 'session.Session',
      rs: 'session.Session',
      go: 'tmux.Session',
      java: 'io.github.libtmux.Session.Session',
      dotnet: 'LibTmux.Session',
      cxx: 'libtmux::Session',
      swift: 'Session',
    },
  },
  window: {
    label: 'A tmux window',
    symbols: {
      py: 'libtmux.Window',
      ts: 'window.Window',
      rs: 'window.Window',
      go: 'tmux.Window',
      java: 'io.github.libtmux.Window.Window',
      dotnet: 'LibTmux.Window',
      cxx: 'libtmux::Window',
      swift: 'Window',
    },
  },
  pane: {
    label: 'A tmux pane',
    symbols: {
      py: 'libtmux.Pane',
      ts: 'pane.Pane',
      rs: 'pane.Pane',
      go: 'tmux.Pane',
      java: 'io.github.libtmux.Pane.Pane',
      dotnet: 'LibTmux.Pane',
      cxx: 'libtmux::Pane',
      swift: 'Pane',
    },
  },
  'capture-pane': {
    label: 'Read a pane’s visible contents',
    symbols: {
      py: 'libtmux.Pane.capture_pane',
      ts: 'pane.Pane.capture',
      rs: 'pane.Pane.capture',
      go: 'tmux.Pane.Capture',
      java: 'io.github.libtmux.Pane.Pane.capture',
      dotnet: 'LibTmux.Pane.CaptureAsync',
      cxx: 'libtmux::Pane::capture',
      swift: 'Server.capture(_:includingHistory:)',
    },
  },
  'send-keys': {
    label: 'Send keystrokes to a pane',
    symbols: {
      py: 'libtmux.Pane.send_keys',
      ts: 'pane.Pane.sendKeys',
      rs: 'pane.Pane.send_keys',
      go: 'tmux.Pane.SendKeys',
      dotnet: 'LibTmux.Pane.SendKeysAsync',
      cxx: 'libtmux::Pane::send_text',
      swift: 'Server.sendKeys(_:to:literally:)',
    },
    absent: {
      java: 'no direct equivalent; `Pane.paste` writes a buffer instead',
    },
  },
  'split-pane': {
    label: 'Split a pane in two',
    symbols: {
      py: 'libtmux.Pane.split',
      ts: 'pane.Pane.split',
      rs: 'pane.Pane.split',
      go: 'tmux.Pane.Split',
      java: 'io.github.libtmux.Pane.Pane.split',
      dotnet: 'LibTmux.Pane.SplitAsync',
      swift: 'Server.split(_:direction:size:startDirectory:)',
    },
    absent: {
      cxx: 'no direct pane target; Window.split splits the active pane',
    },
  },
  'split-window': {
    label: "Split a window's active pane",
    symbols: {
      py: 'libtmux.Window.split',
      ts: 'window.Window.split',
      rs: 'window.Window.split',
      go: 'tmux.Window.SplitPane',
      java: 'io.github.libtmux.Window.Window.split',
      dotnet: 'LibTmux.Window.SplitPaneAsync',
      cxx: 'libtmux::Window::split',
      swift: 'Server.splitWindow(_:direction:size:startDirectory:)',
    },
  },
  'respawn-pane': {
    label: "Restart a pane's command",
    symbols: {
      py: 'libtmux.Pane.respawn',
      ts: 'pane.Pane.respawn',
      rs: 'pane.Pane.respawn',
      go: 'tmux.Pane.Respawn',
      java: 'io.github.libtmux.Pane.Pane.respawn',
      dotnet: 'LibTmux.Pane.RespawnAsync',
      cxx: 'libtmux::Pane::respawn',
      swift: 'Server.respawn(_:running:killingExisting:)',
    },
  },
  'clear-history': {
    label: "Clear a pane's scrollback",
    symbols: {
      py: 'libtmux.Pane.clear_history',
      ts: 'pane.Pane.clearHistory',
      rs: 'pane.Pane.clear_history',
      go: 'tmux.Pane.ClearHistory',
      java: 'io.github.libtmux.Pane.Pane.clearHistory',
      dotnet: 'LibTmux.Pane.ClearHistoryAsync',
      cxx: 'libtmux::Pane::clear_history',
      swift: 'Server.clearHistory(_:)',
    },
  },
  'set-pane-title': {
    label: "Set a pane's title",
    symbols: {
      py: 'libtmux.Pane.set_title',
      ts: 'pane.Pane.setTitle',
      rs: 'pane.Pane.set_title',
      go: 'tmux.Pane.SetTitle',
      java: 'io.github.libtmux.Pane.Pane.retitle',
      dotnet: 'LibTmux.Pane.SetTitleAsync',
      cxx: 'libtmux::Pane::set_title',
      swift: 'Server.setTitle(_:of:)',
    },
  },
  'paste-buffer': {
    label: 'Paste a buffer into a pane',
    symbols: {
      py: 'libtmux.Pane.paste_buffer',
      ts: 'pane.Pane.pasteBuffer',
      rs: 'pane.Pane.paste_buffer',
      go: 'tmux.Pane.PasteBuffer',
      java: 'io.github.libtmux.Pane.Pane.pasteBuffer',
      dotnet: 'LibTmux.Pane.PasteBufferAsync',
      cxx: 'libtmux::Pane::paste',
      swift: 'Server.paste(buffer:into:)',
    },
  },
  'select-layout': {
    label: "Set a window's pane layout",
    symbols: {
      py: 'libtmux.Window.select_layout',
      ts: 'window.Window.selectLayout',
      rs: 'window.Window.select_layout',
      go: 'tmux.Window.SelectLayout',
      java: 'io.github.libtmux.Window.Window.selectLayout',
      dotnet: 'LibTmux.Window.SelectLayoutAsync',
      cxx: 'libtmux::Window::select_layout',
      swift: 'Server.selectLayout(_:_:)',
    },
  },
  'rotate-panes': {
    label: "Rotate panes within a window",
    symbols: {
      py: 'libtmux.Window.rotate',
      ts: 'window.Window.rotate',
      rs: 'window.Window.rotate',
      go: 'tmux.Window.Rotate',
      java: 'io.github.libtmux.Window.Window.rotate',
      dotnet: 'LibTmux.Window.RotateAsync',
      cxx: 'libtmux::Window::rotate',
      swift: 'Server.rotate(_:upward:)',
    },
  },
  'unlink-window': {
    label: 'Unlink a window from a session',
    symbols: {
      py: 'libtmux.Window.unlink',
      ts: 'window.Window.unlink',
      rs: 'window.Window.unlink',
      go: 'tmux.Window.Unlink',
      java: 'io.github.libtmux.Window.Window.unlink',
      dotnet: 'LibTmux.Window.UnlinkAsync',
      cxx: 'libtmux::Window::unlink',
      swift: 'Server.unlink(_:)',
    },
  },
  'source-file': {
    label: 'Load a tmux configuration file',
    symbols: {
      py: 'libtmux.Server.source_file',
      ts: 'server.Server.sourceFile',
      rs: 'server.Server.source_file',
      go: 'tmux.Server.SourceFile',
      java: 'io.github.libtmux.Server.Server.sourceFile',
      dotnet: 'LibTmux.Server.SourceFileAsync',
      cxx: 'libtmux::Server::source_file',
      swift: 'Server.sourceFile(_:)',
    },
  },
  'list-clients': {
    label: "List the server's attached clients",
    symbols: {
      py: 'libtmux.Server.clients',
      ts: 'server.Server.clients',
      rs: 'server.Server.clients',
      go: 'tmux.Server.Clients',
      java: 'io.github.libtmux.Server.Server.clients',
      dotnet: 'LibTmux.Server.Clients',
      cxx: 'libtmux::Server::clients',
      swift: 'Server.clients()',
    },
  },
  'pane-window': {
    label: "Find a pane's containing window",
    symbols: {
      py: 'libtmux.Pane.window',
      ts: 'pane.Pane.window',
      rs: 'pane.Pane.window',
      go: 'tmux.Pane.Window',
      java: 'io.github.libtmux.Pane.Pane.window',
      dotnet: 'LibTmux.Pane.Window',
      cxx: 'libtmux::Pane::window',
    },
    absent: {
      swift: 'no direct accessor; match Pane.windowID against Snapshot.windows',
    },
  },
  'window-session': {
    label: "Find the session containing a window placement",
    symbols: {
      py: 'libtmux.Window.session',
      ts: 'window.Window.session',
      rs: 'window.Window.session',
      go: 'tmux.Window.Session',
      java: 'io.github.libtmux.Window.Window.session',
      dotnet: 'LibTmux.Window.Session',
      cxx: 'libtmux::Window::session',
    },
    absent: {
      swift: 'a Window has no single parent; Snapshot.sessions(of:) lists every linking session',
    },
  },
  'new-session': {
    label: 'Create a session',
    symbols: {
      py: 'libtmux.Server.new_session',
      ts: 'server.Server.newSession',
      rs: 'server.Server.new_session',
      go: 'tmux.Server.NewSession',
      java: 'io.github.libtmux.Server.Server.newSession',
      dotnet: 'LibTmux.Server.CreateSessionAsync',
      cxx: 'libtmux::Server::new_session',
      swift: 'Server.newSession(named:startDirectory:windowName:)',
    },
  },
  'new-window': {
    label: 'Create a window',
    symbols: {
      py: 'libtmux.Session.new_window',
      ts: 'session.Session.newWindow',
      rs: 'session.Session.new_window',
      go: 'tmux.Session.NewWindow',
      java: 'io.github.libtmux.Session.Session.newWindow',
      dotnet: 'LibTmux.Session.CreateWindowAsync',
      cxx: 'libtmux::Session::new_window',
      swift: 'Server.newWindow(in:named:startDirectory:)',
    },
  },
  'kill-server': {
    label: 'Shut the tmux server down',
    symbols: {
      py: 'libtmux.Server.kill',
      ts: 'server.Server.kill',
      rs: 'server.Server.kill',
      go: 'tmux.Server.Kill',
      java: 'io.github.libtmux.Server.Server.killServer',
      dotnet: 'LibTmux.Server.KillAsync',
      cxx: 'libtmux::Server::kill',
      swift: 'Server.killServer()',
    },
  },
  'list-sessions': {
    label: 'List the server’s sessions',
    symbols: {
      py: 'libtmux.Server.sessions',
      ts: 'server.Server.sessions',
      rs: 'server.Server.sessions',
      go: 'tmux.Server.Sessions',
      java: 'io.github.libtmux.Server.Server.sessions',
      dotnet: 'LibTmux.Server.Sessions',
      cxx: 'libtmux::Server::sessions',
      swift: 'Server.sessions()',
    },
  },
  'attach-session': {
    label: 'Attach a client to a session',
    symbols: {
      py: 'libtmux.Session.attach',
      rs: 'control.ControlMode.attach',
      go: 'tmux.Server.AttachSession',
      java: 'io.github.libtmux.control.ControlClient.ControlClient.attach',
      dotnet: 'LibTmux.Server.AttachSessionAsync',
      cxx: 'libtmux::Session::attach_command',
    },
    absent: {
      ts: 'no direct equivalent; the client is out of scope for this port',
      swift: 'reached through `Server.connected(attachingTo:)`, which scopes a block rather than attaching a client',
    },
  },
  'kill-session': {
    label: 'End a session',
    // Swift overloads this method for sessions, windows, and panes.
    symbols: {
      py: 'libtmux.Session.kill',
      ts: 'session.Session.kill',
      rs: 'session.Session.kill',
      go: 'tmux.Session.Kill',
      java: 'io.github.libtmux.Session.Session.kill',
      dotnet: 'LibTmux.Session.KillAsync',
      cxx: 'libtmux::Session::kill',
      swift: 'Server.kill(_:)',
    },
  },
  'kill-window': {
    label: 'Close a window',
    symbols: {
      py: 'libtmux.Window.kill',
      ts: 'window.Window.kill',
      rs: 'window.Window.kill',
      go: 'tmux.Window.Kill',
      java: 'io.github.libtmux.Window.Window.kill',
      dotnet: 'LibTmux.Window.KillAsync',
      cxx: 'libtmux::Window::kill',
      swift: 'Server.kill(_:)',
    },
  },
  'kill-pane': {
    label: 'Close a pane',
    symbols: {
      py: 'libtmux.Pane.kill',
      ts: 'pane.Pane.kill',
      rs: 'pane.Pane.kill',
      go: 'tmux.Pane.Kill',
      java: 'io.github.libtmux.Pane.Pane.kill',
      dotnet: 'LibTmux.Pane.KillAsync',
      cxx: 'libtmux::Pane::kill',
      swift: 'Server.kill(_:)',
    },
  },
  'rename-session': {
    label: 'Rename a session',
    symbols: {
      py: 'libtmux.Session.rename_session',
      ts: 'session.Session.rename',
      rs: 'session.Session.rename',
      go: 'tmux.Session.Rename',
      java: 'io.github.libtmux.Session.Session.rename',
      dotnet: 'LibTmux.Session.RenameAsync',
      cxx: 'libtmux::Session::rename',
      swift: 'Server.rename(_:to:)',
    },
  },
  'rename-window': {
    label: 'Rename a window',
    symbols: {
      py: 'libtmux.Window.rename_window',
      ts: 'window.Window.rename',
      rs: 'window.Window.rename',
      go: 'tmux.Window.Rename',
      java: 'io.github.libtmux.Window.Window.rename',
      dotnet: 'LibTmux.Window.RenameAsync',
      cxx: 'libtmux::Window::rename',
      swift: 'Server.rename(_:to:)',
    },
  },
  'select-window': {
    label: 'Make a window active',
    symbols: {
      py: 'libtmux.Window.select',
      ts: 'window.Window.select',
      rs: 'window.Window.select',
      go: 'tmux.Window.Select',
      java: 'io.github.libtmux.Window.Window.select',
      dotnet: 'LibTmux.Window.SelectAsync',
      cxx: 'libtmux::Window::select',
      swift: 'Server.select(_:)',
    },
  },
  'select-pane': {
    label: 'Make a pane active',
    symbols: {
      py: 'libtmux.Pane.select',
      ts: 'pane.Pane.select',
      rs: 'pane.Pane.select',
      go: 'tmux.Pane.Select',
      java: 'io.github.libtmux.Pane.Pane.select',
      dotnet: 'LibTmux.Pane.SelectAsync',
      cxx: 'libtmux::Pane::select',
      swift: 'Server.select(_:)',
    },
  },
  'resize-pane': {
    label: 'Resize a pane',
    symbols: {
      py: 'libtmux.Pane.resize',
      ts: 'pane.Pane.resize',
      rs: 'pane.Pane.resize',
      go: 'tmux.Pane.Resize',
      java: 'io.github.libtmux.Pane.Pane.resize',
      dotnet: 'LibTmux.Pane.ResizeAsync',
      swift: 'Server.resize(_:width:height:)',
    },
    absent: {
      cxx: 'no direct equivalent; `libtmux::Window::resize` resizes the window, not a pane within it',
    },
  },
  'list-windows': {
    label: "List a session's windows",
    symbols: {
      py: 'libtmux.Session.windows',
      ts: 'session.Session.windows',
      rs: 'session.Session.windows',
      go: 'tmux.Session.Windows',
      java: 'io.github.libtmux.Session.Session.windows',
      dotnet: 'LibTmux.Session.Windows',
      cxx: 'libtmux::Session::windows',
      swift: 'Snapshot.windows(of:)',
    },
  },
  'list-panes': {
    label: "List a window's panes",
    symbols: {
      py: 'libtmux.Window.panes',
      ts: 'window.Window.panes',
      rs: 'window.Window.panes',
      go: 'tmux.Window.Panes',
      java: 'io.github.libtmux.Window.Window.panes',
      dotnet: 'LibTmux.Window.Panes',
      cxx: 'libtmux::Window::panes',
      swift: 'Snapshot.panes(of:)',
    },
  },
  'list-session-panes': {
    label: "List a session's panes",
    symbols: {
      py: 'libtmux.Session.panes',
      ts: 'session.Session.panes',
      rs: 'session.Session.panes',
      go: 'tmux.Session.Panes',
      dotnet: 'LibTmux.Session.Panes',
      cxx: 'libtmux::Session::panes',
      swift: 'Snapshot.panes(of:)',
    },
    absent: {
      java: 'no direct accessor; traverse Session.windows and Window.panes',
    },
  },
  'list-server-windows': {
    label: "List the server's windows",
    symbols: {
      py: 'libtmux.Server.windows',
      ts: 'server.Server.windows',
      rs: 'server.Server.windows',
      go: 'tmux.Server.Windows',
      java: 'io.github.libtmux.Server.Server.windows',
      dotnet: 'LibTmux.Server.Windows',
      cxx: 'libtmux::Server::windows',
      swift: 'Server.windows()',
    },
  },
  'list-server-panes': {
    label: "List the server's panes",
    symbols: {
      py: 'libtmux.Server.panes',
      ts: 'server.Server.panes',
      rs: 'server.Server.panes',
      go: 'tmux.Server.Panes',
      java: 'io.github.libtmux.Server.Server.panes',
      dotnet: 'LibTmux.Server.Panes',
      cxx: 'libtmux::Server::panes',
      swift: 'Server.panes()',
    },
  },
  'active-window': {
    label: "The session's active window",
    symbols: {
      py: 'libtmux.Session.active_window',
      ts: 'session.Session.activeWindow',
      rs: 'session.Session.active_window',
      go: 'tmux.Session.ActiveWindow',
      java: 'io.github.libtmux.Session.Session.activeWindow',
      dotnet: 'LibTmux.Session.ActiveWindow',
      cxx: 'libtmux::Session::active_window',
    },
    absent: {
      swift: 'no accessor; `Pane.isActive` is a flag on the pane, so the active one is found by filtering a listing',
    },
  },
  'active-pane': {
    label: "The window's active pane",
    symbols: {
      py: 'libtmux.Window.active_pane',
      ts: 'window.Window.activePane',
      rs: 'window.Window.active_pane',
      go: 'tmux.Window.ActivePane',
      java: 'io.github.libtmux.Window.Window.activePane',
      dotnet: 'LibTmux.Window.ActivePane',
      cxx: 'libtmux::Window::active_pane',
    },
    absent: {
      swift: 'no accessor; `Pane.isActive` is a flag on the pane, so the active one is found by filtering a listing',
    },
  },
  'server-alive': {
    label: 'Whether the server is running',
    symbols: {
      py: 'libtmux.Server.is_alive',
      ts: 'server.Server.isAlive',
      rs: 'server.Server.is_alive',
      go: 'tmux.Server.IsAlive',
      java: 'io.github.libtmux.Server.Server.isAlive',
      dotnet: 'LibTmux.Server.IsAliveAsync',
      cxx: 'libtmux::Server::is_alive',
      swift: 'Server.isRunning()',
    },
  },
}

/** Every concept naming this symbol, including concepts sharing an overload group. */
export function conceptsFor(port: string, publicId: string): Concept[] {
  return Object.values(CONCEPTS).filter((c) => c.symbols[port] === publicId)
}
